version: 0.2

phases:
  build:
    commands:
      - echo "Building Spring Boot application..."
      - mvn clean package
      - mkdir -p deploy
      - cp target/*.jar deploy/application.jar
      - cp -r .ebextensions deploy/

  post_build:
    commands:
      - echo "Zipping artifact for deployment..."
      - cd deploy
      - zip -r ../deploy.zip .
      - cd ..
      - echo "Build and packaging completed successfully"

artifacts:
  files:
    - deploy.zip
  discard-paths: yes
