version: 0.2

phases:
  build:
    commands:
      - echo "Building Spring Boot application..."
      - mvn clean package

  post_build:
    commands:
      - echo "Build complete successfully"
      - cp target/*.jar cinema-service.jar

artifacts:
  files:
    - cinema-service.jar

