version: 0.2

phases:
  build:
    commands:
      - echo "Building Spring Boot application..."
      - mvn clean package

  post_build:
    commands:
      - echo "Build complete successfully"

artifacts:
  files:
    - target/cinema-service.jar
  discard-paths: yes
